#!/usr/bin/env bash
# CustomPiOS auto-mount-removable media module
# Script sets that devices would be automatically mounted to /media
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -x
set -e

source /common.sh

case "${BASE_DISTRO}" in
  redhat|rocky|centos)
    # TODO: usbmount missing package
    ;;
  *)
    apt-get update --allow-releaseinfo-change
    apt-get install -y usbmount
    ;;
esac

unpack /filesystem/root /
