#!/usr/bin/env bash
# 
# Copyright 2021 by Stephan Wendel aka KwadFan
# <me@stephanwe.de>
# This file may distributed under GPLv3
########

### Cleanup
case "${BASE_DISTRO}" in
  redhat|rocky|centos)
    dnf clean all
    ;;
  *)
    apt-get clean
    apt-get autoremove -y
    ;;
esac

